### ISSUE TITLE
Unexpected Error Occurs When Replaying an Ad in Some Web Browsers

### ISSUE THREAD

**Issue by treid003** [webrecorder/replayweb.page#157] opened 2023-02-15 19:11 UTC
WACZ file used: [2023-01-26-ads-on-scmp.wacz](https://olddominion-my.sharepoint.com/:u:/g/personal/treid003_odu_edu/EUXtiRpsDJtNtu_wKKC_RFgBxO4Jjh0ZlGbxla2dJyeYvQ?e=3Rm2bu) 

When attempting to replay an ad, an unexpected error occurred when using some browsers. When I used Firefox, the image needed for an ad was successfully loaded by ReplayWeb.page.
![successfully_replayed](https://user-images.githubusercontent.com/31581841/219122981-120479f4-2eca-4137-9bad-c74f967c0707.png)

When I used Chrome, ReplayWeb.page desktop app, Edge, Opera, and Safari, the image for the ad did not load. During the replay of this ad in these browsers the HTTP headers for the image included a 404 status code.
![http_headers_during_replay](https://user-images.githubusercontent.com/31581841/219123210-ce7b4ada-66f2-4562-94d2-a40e305d498f.png)

When viewing the response tab in developer tools it showed the code associated with ReplayWeb.page’s [404.html](https://github.com/webrecorder/replayweb.page/blob/main/404.html) file.
![404_html_file_in_response](https://user-images.githubusercontent.com/31581841/219123376-62c00930-a9b6-4d90-8dd8-07fdbfcad56e.png)

This was an unexpected 404 status code, since the image’s HTTP headers include a 200 status code in the data.warc.gz file.
![image_http_headers](https://user-images.githubusercontent.com/31581841/219123528-46ef35e8-e782-44e0-b712-c21afc1b5de4.png)

The web archiving tool I used to archive this web page was the ArchiveWeb.page Chrome extension.

Do you know why replaying this ad works in Firefox, but does not work in other web browsers?

**Comment by ikreymer** [comment] 2023-02-25 03:37
Unfortunately, I think this is due to a bug in Chromium-based browserse where about:blank iframes created from a page that is controlled by a service worker is not immediately controlled, and therefore requests on it 'leak' to the upstream server.
You can see this by running a local version of replayweb.page with just say `http-server -p 9990` and see that certain ad related requests 'leak' to the server when loaded in Chrome, but not in FF. The image you mention is one of those URLs, resulting in a 404.

I think the issue is likely: https://bugs.chromium.org/p/chromium/issues/detail?id=880768
While wombat tries to address this by having iframes load from a custom about:blank and srcdoc pages served by the service worker, I think there's still a race condition where the ad frames create an about:blank page, then immediately write to it with document.write() or load some resources like (new Image().src synchronously) which starts to load before the SW can take control of the page..
Firefox did a better job of fixing this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1350850

In the case of the ReplayWeb.page app, it can actually catch these URLs and still handled them, so the ad does actually load from this page. Hopefully that issue will be fixed in Chrome at some point...

**Comment by treid003** [comment] 2023-03-07 00:33
Ok, thanks.

**Comment by ikreymer** [comment] 2023-03-07 03:40
Good News! Since original comment, there seems to actaully be a fix for this (see the linked commit). We can override document.write with a URL loaded from service worker that loads a blob, which generally fixes the issue!

**Comment by treid003** [comment] 2023-03-07 19:48
When I recently used the local version of ReplayWeb.page, it did not successfully replay the ad. It seems like some requests are still leaking to the upstream server.

Video: <https://youtu.be/ow2VT0Bc5nk>

![2023-03-07_leaked_request](https://user-images.githubusercontent.com/31581841/223533193-f724b883-9613-402d-8d01-aa459840dc8f.png)

**Comment by ikreymer** [comment] 2023-04-06 17:57
This should now be fixed in 1.7.14

**Closed by ikreymer** 2023-04-06 17:57 UTC

**Comment by treid003** [comment] 2023-04-10 21:39
Yes, it is working now. Thank you.
