### ISSUE TITLE
Incorretly decoding URLs or not correctly loading images

### ISSUE THREAD

**Issue by DrMint** [webrecorder/replayweb.page#64] opened 2021-08-14 09:12 UTC
Hi,
I've been experimenting with browsertrix-crawler and replayweb.page for a few weeks now, it's great!
However, I just encounter a problem with Replaying a warcz file generated by browsertrix-crawler.

![image](https://user-images.githubusercontent.com/29893320/129441031-acc39121-0807-4679-b645-624178d56bea.png)

Here is the problem: the top window is one of the warc file where I opened an image (original url of the image: https://img.atwikiimg.com/www65.atwiki.jp/sinoalice_kousatu/attach/40/212/%E3%82%A2%E3%83%AA%E3%82%B9%E8%A1%9D%E5%8B%9525.jpg)

And now the bottom window is the exact same image but from the warcz file (generated with the option --generateWACZ). This time, the image doesn't load.

Both the warc files and the warcz file are roughly the same size so I'm guessing the data is there.

Here's the exact command I used for generating the archive:
`docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --url https://w.atwiki.jp/sinoalice_kousatu --include "https:\/\/w\.atwiki\.jp\/sinoalice_kousatu|https:\/\/img\.atwikiimg\.com" --ex
clude "\/copy2\/|\/pedit\/|\/child\/|\/editx\/|\/renamex\/|\/editxx\/|\/chmod\/|\/chkind\/" --workers 3 --text --generateWACZ`

Edit: I initially though it was because of the Japanese characters, but no, here's another example without any characters outside of the typical Latin character-set:

![image](https://user-images.githubusercontent.com/29893320/129441013-904c0b42-7b25-430f-8022-c61611b08a11.png)

Edit2: here's the execution log in case there is something important there:

```
Text Extraction: Enabled
Load timeout for https://w.atwiki.jp/sinoalice_kousatu/pages/35.html TimeoutError: Navigation timeout of 90000 ms exceeded
    at /app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111

== Start:     2021-08-14 07:06:20.518
== Now:       2021-08-14 08:17:22.477 (running for 1.2 hours)
== Progress:  5198 / 5198 (100.00%), errors: 1 (0.02%)
== Remaining: 0.0 ms (@ 1.22 pages/second)
== Sys. load: 53.3% CPU / 90.8% memory
== Workers:   3
   #0 IDLE
   #1 IDLE
   #2 IDLE
Waiting to ensure pending data is written to WARCs...
Generating WACZ
Validating passed pages.jsonl file
Reading and Indexing All WARCs
Writing archives...
Generating page index from passed pages...
Header detected in the passed pages.jsonl file
Generating datapackage.json
Generating datapackage-digest.json
```

**Comment by DrMint** [comment] 2021-08-14 10:04
I have tried again at smaller scale with this command:
``docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --url https://w.atwiki.jp/sinoalice_kousatu/pages/31.html --include "31|https:\/\/img\.atwikiimg\.com" --workers 3 --text --generateW
ACZ`

Unfortunately, it's not replicating the problem.
That being said, I also tried:
`docker run -v $PWD/crawls:/crawls/ -it webrecorder/browsertrix-crawler crawl --url https://w.atwiki.jp/sinoalice_kousatu/pages/31.html --text --generateWACZ --depth 0`

and when clicking on a missing image, it cannot even load the live page image:
![image](https://user-images.githubusercontent.com/29893320/129442493-0ae3e5d1-c68e-4678-97da-ccc50d6f83cf.png)
despite the image being available online if we copy/paste the link into a browser.
I'm wondering if this could be a misinterpretation of the URL? I see it's adding "null" at the end.

**Comment by ikreymer** [comment] 2021-08-14 17:02
Thanks for reporting, Could you share the original WARC and WACZ that are loading differently? You can share them via email if you'd like.

The last issue could be something else, so want to look at one thing at a time. (The 'null' at the end bug was fixed in the replayweb.page hosted version, and will be in the next app release coming shortly as well)

**Comment by DrMint** [comment] 2021-08-14 22:43
Of course here's a [link](https://drive.google.com/file/d/10gnabnd2MhGU4TvILOgPcd6ib1Z8c8mk/view?usp=sharing) to the collection it created in my first example. I wish I could have recreated this problem on a smaller crawl but I'm haven't been able to make the seed and config file work so I'm limited to the command line parameters.

The image in the first screenshot was located in `rec-20210814070623379161-76e848972cc4.warc.gz`

Just for clarity, one problem I had with this crawl is that the wiki uses collapsible on most pages (content hiding until you click on a + button). This images displayed within those collapsed section are lazy-loaded so they are not included in the recording. In order to download them, I avoided including the /upload/XXX.html pages which content a list of all the images included in page XXX. And those images are seemingly always stored on another domain (img.atwikiimg.com).

**Comment by DrMint** [comment] 2021-08-14 23:13
Okay so same behavior after using py-wacz, but I think I understood a lot of things.

In the WARCs, theses images are categorized in the URLs tab, and in the WARCZ, they are in the Pages tab. None of the images URLs works when they are considered pages (which could make sense if it expects a HTML MIME. There are actually 146 images in the URL tab from the domain https://img.atwikiimg.com in the resulting WARCZ, and they work perfectly. The images are from https://w.atwiki.jp/sinoalice_kousatu/pages/100.html, https://w.atwiki.jp/sinoalice_kousatu/pages/99.html, and https://w.atwiki.jp/sinoalice_kousatu/pages/98.html, and sure enough, those pages have all the images displayed when browsing them.

Also there are WAY more images in the WARCs then the resulting WARCZ: when searching of "https://img.atwikiimg.com" in URLs and Pages, we get a total of 171 images. When doing the same in rec-20210814070623379161-76e848972cc4.warc.gz, there is none in the Pages, but 854 in the URLs.

**Comment by ikreymer** [comment] 2021-08-15 22:05
Thanks for reporting, I think I've been able to repro the issue with the images and am taking a look.

**Comment by ikreymer** [comment] 2021-08-16 21:20
Thanks for reporting, the main issue was that the URLs that had a `www65.` in them were being incorrectly canonicalized (due to a bug in warcio.js), preventing them from being loaded! This was specific to this URL pattern, and quite an edge case, but glad it was detected.

The pages in the WACZ should work now in the latest replayweb.page site.

There's a separate issue about images not loading in the prefix query in the URL tab, that will be fixed in a follow up update.
There should be no difference with how a page loads via either the WARC or the WACZ. (The page I tested specifically was `https://w.atwiki.jp/sinoalice_kousatu/pages/98.html`).

(There is also the ad images, which appear to load in Firefox but not chrome, but that's a separate, complicated issue)

Let us know if the issue is still happening.

**Comment by DrMint** [comment] 2021-08-17 06:11
Hi! I've just quickly skimmed through the archive using the latest version, and it seems like everything is loading fine now: awesome! I'm glad this got fixed because other than that, it's the best set of tools I've found for the purpose of archiving and replaying websites. Thanks a bunch!

**Closed** 2021-08-20 10:38 UTC
