### ISSUE TITLE
Chrome browser crashed when trying to replay a FB archive

### ISSUE THREAD

**Issue by dteyssou** [webrecorder/replayweb.page#230] opened 2023-09-04 12:24 UTC
Chrome browser (version 116.0.5845.140 on MacOs Ventura 13.4.1) crashes when trying to replay a FB page archive recorded with webrecorder extension. 
The crash occurs when using replayweb within the webrecorder plugin. The website replayweb.page works with the same files.

**Comment by ikreymer** [comment] 2024-07-08 03:37
This is really a duplicate of webrecorder/archiveweb.page#194 and has been fixed there.

**Closed by ikreymer** 2024-07-08 03:37 UTC
