### ISSUE TITLE
Loading local files in Firefox (was: Charset issues in Firefox but not in Chrome)

### ISSUE THREAD

**Issue by awendland** [webrecorder/replayweb.page#7] opened 2020-07-09 00:51 UTC
Hello! First off, thank you so much for creating this tool. It's really awesome and it's got me really excited about the future for web archiving.

While working on archiving a webpage for someone ([here's the warc.gz](https://drive.google.com/file/d/1-GPuxdZKr4fs5NalQxCFujjf5OTke5B2/view?usp=sharing) I produced) I ran into an issue with Firefox (version 79.0b5 (64-bit)):

<img width="589" alt="Screen Shot 2020-07-08 at 5 31 34 PM" src="https://user-images.githubusercontent.com/1152104/86983702-6fbe5100-c141-11ea-9334-13420f967904.png">

It got to the loading screen but never progressed past 0%. Since then the page has no longer responded to any clicks or user interaction, even after a reload.

It loads fine on Chromium (version 86.0.4185.0) however.

I was trying to debug the error but I couldn't figure out where it was coming from since there weren't any line numbers and I couldn't find the error message in this repository. I'm not sure the error message is even related to the freezup. Since I have a workaround I don't need to be unblocked, but I'd love out with making this project more robust if possible (if this is a user issue then sorry for wasting your time!).

**Comment by ikreymer** [comment] 2020-07-10 05:05
This seems like another manifestation of an issue with Firefox in loading local files in a web worker.
I've reported this issue here: https://bugzilla.mozilla.org/show_bug.cgi?id=1646204 with a reliable test case.
I initially ran into this with files around 50MB, but now it seems like its happening for even smaller files, like the 15MB that you have.

By the way, you can also load directly from Google drive as well, if you install the google drive integration:
https://gsuite.google.com/marketplace/app/replaywebpage/160798412227

With the drive loading, it worked slightly better in Firefox.. (didn't load all the way the first time, loaded the second time for me). I'm guessing its probably a variation of the same issue, seems like Firefox just doesn't work well with streaming data in a web worker, surprisingly..

My guess is the work around is probably to load the file not in a web worker, but in the main thread, and just process it there, or send to worker via channel/postmessage for processing.. Would require some refactoring, but should be doable..
I think the charset is probably unrelated, so changed the title of the issue..

Yes, would definitely welcome help in fixing this issue! Maybe there's a different workaround that's possible, or something else that I'm missing, but I think the example in the issue covers it. I believe the issue is that it simply stalls reading from the ReadableStream -- await read() never resolves nor rejects, and it happens at random points in the stream :(

**Comment by ikreymer** [comment] 2021-03-15 04:58
ReplayWeb.page now loads everything in the service worker, awaits a promise while loading, and there's a ping every 15 seconds to prevent service worker from shutting down. With that, I believe Firefox loading is working, not as fast as Chrome, but it does finish. Just tested with the WARC shared here, which fully loaded in FF, so I believe this should be fixed!

**Closed by ikreymer** 2021-03-15 04:58 UTC
